site_name: JB Docs
repo_url: https://github.com/jonasbirkelof/docs
repo_name: jonasbirkelof/docs
copyright: Copyright &copy; 2023 - 2024 Jonas Birkel&#246;f

# Configuration
theme:
  name: material
  custom_dir: docs/overrides/
  logo: assets/images/jb_logo_col_transparent.svg
  logo_dark: assets/images/jb_logo_wht_transparent.svg
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: fontawesome/regular/moon
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: fontawesome/regular/sun
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy
extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/steps.css
plugins:
  - search
  - glightbox:
       skip_classes:
         - skip-lightbox
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
# nav:
#   # Home
#   - Home:
#     - Welcome: index.md
#   - Tech:
#     - Windows:
#       - tech/windows/install-git-on-windows.md
#       - tech/windows/edge-taskbar.md
#   - Media:
#     - media/naruto-movies-episodes.md