authors:
  jonasbirkelof:
    name: Jonas Birkelöf
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/61730892?v=4
    slug: jonasbirkelof
    url: https://github.com/jonasbirkelof